# Billetterie Service - Production Configuration
server:
  port: 8092

spring:
  application:
    name: billetterieservice
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true

  datasource:
    url: jdbc:postgresql://postgresdb:5433/${POSTGRES_DB:billetteriedb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29093}
    template:
      default-topic: NOTIFICATION_TOPIC
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          type:
            mapping: Notification:io.multi.billetterieservice.domain.Notification

eureka:
  instance:
    hostname: billetterieservice
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:manager}:${EUREKA_PASSWORD:manager2711}@discoveryserver:8761/eureka/

ui:
  app:
    url: ${UI_APP_URL:https://guidipress-io.com}

key:
  private: private.key
  public: public.key

jwks:
  uri: ${JWKS_URI:http://authorizationserver:8090/authorization/oauth2/jwks}

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG
