# Discovery Server - Production Configuration
spring:
  application:
    name: discoveryserver
  datasource:
    url: jdbc:postgresql://postgresdb:5433/${POSTGRES_DB:billetteriedb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

eureka:
  instance:
    hostname: discoveryserver
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${EUREKA_USER:manager}:${EUREKA_PASSWORD:manager2711}@discoveryserver:8761/eureka/
  server:
    expected-client-renewal-interval-seconds: 10
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    wait-time-in-ms-when-sync-empty: 5000
    peer-node-read-timeout-ms: 30000

server:
  port: 8761

logging:
  level:
    root: INFO
    com.netflix: WARN
